### ISSUE TITLE
[QUESTION] ControllerX Not working on fresh HA install

### ISSUE THREAD

**Issue by Meisteryoda1994** [xaviml/controllerx#1025]
I started a fresh HA installation and uses my old apps.yaml file for controllerX. I placed it in the correct folder. 
in my old installation everything works fine but in my new installation it won't work. 

I run everything on the latest software 

<img width="488" alt="Scherm­afbeelding 2024-08-24 om 19 54 49" src="https://github.com/user-attachments/assets/41761ad9-ecce-4164-bdbc-9ddcc3749d43">

**Comment by xaviml** [comment]
Hi @Meisteryoda1994 , have you changed the "app_dir" attribute from appdaemon.yaml?

You can follow these instructions: https://controllerx.netlify.app/controllerx/start/installation/

**Comment by Meisteryoda1994** [comment]
HI, Yes I did it and still no results

**Comment by xaviml** [comment]
Can you show the AppDaemon logs? I first need to know if it is picking the right AppDaemon logs.

Can you also share the appdaemon.yaml file as well as its location?

**Comment by Meisteryoda1994** [comment]
@xaviml 

The location is  : smb://homeassistant/addon_configs/a0d7b954_appdaemon/appdaemon.yaml

the code is:
`---
secrets: /homeassistant/secrets.yaml
app_dir: /homeassistant/appdaemon/apps/
appdaemon:
  latitude: xxx
  longitude: xxx
  elevation: 2
  time_zone: Europe/Amsterdam
  plugins:
    HASS:
      type: hass
http:
  url: http://127.0.0.1:5050
admin:
api:
hadashboard:`






THe loggs
`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

-----------------------------------------------------------
 Add-on: AppDaemon
 Python Apps and Dashboard using AppDaemon 4.x for Home Assistant
-----------------------------------------------------------
 Add-on version: 0.16.6
 You are running the latest version of this add-on.
 System: Home Assistant OS 13.1  (amd64 / generic-x86-64)
 Home Assistant Core: 2024.8.2
 Home Assistant Supervisor: 2024.08.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-appdaemon: starting
s6-rc: info: service init-appdaemon successfully started
s6-rc: info: service appdaemon: starting
s6-rc: info: service appdaemon successfully started
s6-rc: info: service legacy-services: starting
[11:33:45] INFO: Starting AppDaemon...
s6-rc: info: service legacy-services successfully started
2024-08-25 11:33:47.686800 INFO AppDaemon: AppDaemon Version 4.4.2 starting
2024-08-25 11:33:47.686978 INFO AppDaemon: Python version is 3.11.9
2024-08-25 11:33:47.687147 INFO AppDaemon: Configuration read from: /config/appdaemon.yaml
2024-08-25 11:33:47.687333 INFO AppDaemon: Added log: AppDaemon
2024-08-25 11:33:47.687519 INFO AppDaemon: Added log: Error
2024-08-25 11:33:47.687702 INFO AppDaemon: Added log: Access
2024-08-25 11:33:47.687835 INFO AppDaemon: Added log: Diag
2024-08-25 11:33:47.802690 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2024-08-25 11:33:47.915378 INFO HASS: HASS Plugin Initializing
2024-08-25 11:33:47.915517 WARNING HASS: ha_url not found in HASS configuration - module not initialized
2024-08-25 11:33:47.915662 INFO HASS: HASS Plugin initialization complete
2024-08-25 11:33:47.915989 INFO AppDaemon: Initializing HTTP
2024-08-25 11:33:47.916251 INFO AppDaemon: Using 'ws' for event stream
2024-08-25 11:33:47.918740 INFO AppDaemon: Starting API
2024-08-25 11:33:47.920042 INFO AppDaemon: Starting Admin Interface
2024-08-25 11:33:47.920308 INFO AppDaemon: Starting Dashboards
2024-08-25 11:33:47.928411 INFO HASS: Connected to Home Assistant 2024.8.2
2024-08-25 11:33:47.934020 INFO AppDaemon: App 'hello_world' added
2024-08-25 11:33:47.934622 INFO AppDaemon: Found 1 active apps
2024-08-25 11:33:47.934793 INFO AppDaemon: Found 0 inactive apps
2024-08-25 11:33:47.934970 INFO AppDaemon: Found 0 global libraries
2024-08-25 11:33:47.935145 INFO AppDaemon: Starting Apps with 1 workers and 1 pins
2024-08-25 11:33:47.935591 INFO AppDaemon: Running on port 5050
2024-08-25 11:33:47.955149 INFO HASS: Evaluating startup conditions
2024-08-25 11:33:47.960099 INFO HASS: Startup condition met: hass state=RUNNING
2024-08-25 11:33:47.960326 INFO HASS: All startup conditions met
2024-08-25 11:33:47.978876 INFO AppDaemon: Got initial state from namespace default
2024-08-25 11:33:49.940641 INFO AppDaemon: Scheduler running in realtime
2024-08-25 11:33:49.946427 INFO AppDaemon: Adding /config/apps to module import path
2024-08-25 11:33:49.950164 INFO AppDaemon: Loading App Module: /config/apps/hello.py
2024-08-25 11:33:49.997124 INFO AppDaemon: Loading app hello_world using class HelloWorld from module hello
2024-08-25 11:33:49.998069 INFO AppDaemon: Calling initialize() for hello_world
2024-08-25 11:33:50.026699 INFO hello_world: Hello from AppDaemon
2024-08-25 11:33:50.027331 INFO hello_world: You are now ready to run Apps!
2024-08-25 11:33:50.028150 INFO AppDaemon: App initialization complete
2024-08-25 11:37:36.435604 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2024-08-25 11:37:41.453042 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2024-08-25 11:37:46.466109 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2024-08-25 11:37:48.151923 WARNING HASS: Error getting services - retrying
Task exception was never retrieved
future: <Task finished name='Task-93' coro=<HassPlugin.run_hass_service_check() done, defined at /usr/lib/python3.11/site-packages/appdaemon/plugins/hass/hassplugin.py:763> exception=ClientResponseError(RequestInfo(url=URL('http://supervisor/core/api/services'), method='GET', headers=<CIMultiDictProxy('Host': 'supervisor', 'x-ha-access': '80dc885ce11bc84d9d0d809e021ff3c2a06dcefafe3cce56aa29789e5b7519971d1dcf4d6a4be1dfa3c9bb28d9425cfb07c083cf2771b65a', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Python/3.11 aiohttp/3.8.6')>, real_url=URL('http://supervisor/core/api/services')), (), status=502, message='Bad Gateway', headers=<CIMultiDictProxy('Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '16', 'Date': 'Sun, 25 Aug 2024 09:37:48 GMT', 'Server': 'Python/3.12 aiohttp/3.9.5')>)>
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/plugins/hass/hassplugin.py", line 772, in run_hass_service_check
    hass_services = await self.get_hass_services()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/appdaemon/plugins/hass/hassplugin.py", line 732, in get_hass_services
    r.raise_for_status()
  File "/usr/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1011, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 502, message='Bad Gateway', url=URL('http://supervisor/core/api/services')
2024-08-25 11:37:51.470767 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2024-08-25 11:37:56.483572 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2024-08-25 11:38:01.497043 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2024-08-25 11:38:06.508352 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2024-08-25 11:38:11.522354 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2024-08-25 11:38:16.541987 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2024-08-25 11:38:21.557424 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2024-08-25 11:38:26.562686 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2024-08-25 11:38:31.573430 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2024-08-25 11:38:36.595485 INFO HASS: Connected to Home Assistant 2024.8.2
2024-08-25 11:38:36.691418 INFO HASS: Evaluating startup conditions
2024-08-25 11:38:36.702589 INFO HASS: Startup condition met: hass state=RUNNING
2024-08-25 11:38:36.702825 INFO HASS: All startup conditions met
2024-08-25 11:38:36.736275 INFO AppDaemon: Processing restart for HASS
2024-08-25 11:38:36.736554 INFO AppDaemon: Terminating hello_world
2024-08-25 11:38:36.737289 INFO AppDaemon: Reloading Module: /config/apps/hello.py
2024-08-25 11:38:36.738692 INFO AppDaemon: Loading app hello_world using class HelloWorld from module hello
2024-08-25 11:38:36.740055 INFO AppDaemon: Calling initialize() for hello_world
2024-08-25 11:38:36.741271 INFO hello_world: Hello from AppDaemon
2024-08-25 11:38:36.742083 INFO hello_world: You are now ready to run Apps!`

**Comment by Meisteryoda1994** [comment]
The AppDeamon.yaml file is when I open (with samba share)HA Server In the Addon_configs. there is a folder called "a0d7b954_appdaemon"

The code from the appdeamon.yaml file I use is 1-1 copy (with other coordinates location)

then inside homeassistant  there is also a config folder.  when I open that I get a folder with the name Appdeamon.

inside that folder is a folder called Apps. inside that folder is a folder called controllerX and the apps.yaml file. 

so I think everything is in the right spot


<img width="1095" alt="Scherm­afbeelding 2024-08-25 om 12 13 16" src="https://github.com/user-attachments/assets/358e89c4-52d0-4245-b9c3-c5f40267ee39">
<img width="1045" alt="Scherm­afbeelding 2024-08-25 om 12 12 58" src="https://github.com/user-attachments/assets/65416b22-b572-4a25-9e7b-057d5e48ff3c">

**Comment by xaviml** [comment]
Can you show an screenshot of the appdaemon.yaml content?

**Comment by Meisteryoda1994** [comment]
yes, 
<img width="496" alt="Scherm­afbeelding 2024-08-25 om 12 29 28" src="https://github.com/user-attachments/assets/23f48e12-a27c-4d03-874f-fa046bdbdb01">

**Comment by Meisteryoda1994** [comment]
yes
<img width="520" alt="Scherm­afbeelding 2024-08-25 om 12 32 28" src="https://github.com/user-attachments/assets/2d2fe312-f296-43f2-ac76-21c9ea6f60e8">

**Comment by xaviml** [comment]
All the files and logs you are showing are not coherent since the apps dir is pointed to a directory with controllerx app, but the AppDaemon logs show the Hello app loading. So, I am not sure where the issue is, but it seems to be related to not picking up the right appdaemon.yaml file maybe.

**Comment by xaviml** [comment]
You can see this in the logs:

2024-08-25 11:33:49.946427 INFO AppDaemon: Adding /config/apps to module import path
2024-08-25 11:33:49.950164 INFO AppDaemon: Loading App Module: /config/apps/hello.py

**Comment by Meisteryoda1994** [comment]
i have this in the log now:

`2024-08-25 12:48:43.557468 INFO AppDaemon: Adding thread 1
2024-08-25 12:48:43.557863 INFO AppDaemon: Adding thread 2
2024-08-25 12:48:43.558242 INFO AppDaemon: Adding thread 3
2024-08-25 12:48:43.558595 INFO AppDaemon: Adding thread 4
2024-08-25 12:48:43.558941 INFO AppDaemon: Adding thread 5
2024-08-25 12:48:43.559330 INFO AppDaemon: Adding thread 6
2024-08-25 12:48:43.559735 INFO AppDaemon: Adding thread 7
2024-08-25 12:48:43.560161 INFO AppDaemon: Adding thread 8
2024-08-25 12:48:43.561898 INFO AppDaemon: Loading app Volume_woonkamer using class E1744MediaPlayerController from module controllerx
2024-08-25 12:48:43.562102 WARNING AppDaemon: Unable to find module module controllerx - 'Volume_woonkamer' is not loaded
2024-08-25 12:48:43.562451 INFO AppDaemon: Loading app Zolder_verlichting_switch using class W2049LightController from module controllerx
2024-08-25 12:48:43.562630 WARNING AppDaemon: Unable to find module module controllerx - 'Zolder_verlichting_switch' is not loaded
2024-08-25 12:48:43.562965 INFO AppDaemon: Loading app Volume_slaapkamer using class E1744MediaPlayerController from module controllerx
2024-08-25 12:48:43.563144 WARNING AppDaemon: Unable to find module module controllerx - 'Volume_slaapkamer' is not loaded
2024-08-25 12:48:43.563465 INFO AppDaemon: Loading app Nachtlampje_rosalie using class E1743Controller from module controllerx
2024-08-25 12:48:43.563639 WARNING AppDaemon: Unable to find module module controllerx - 'Nachtlampje_rosalie' is not loaded
2024-08-25 12:48:43.563971 INFO AppDaemon: Loading app washoek_switch using class E1743Controller from module controllerx
2024-08-25 12:48:43.564146 WARNING AppDaemon: Unable to find module module controllerx - 'washoek_switch' is not loaded
2024-08-25 12:48:43.564463 INFO AppDaemon: Loading app Feestlampen_schuur_styrvar_switch using class E2002LightController from module controllerx
2024-08-25 12:48:43.564638 WARNING AppDaemon: Unable to find module module controllerx - 'Feestlampen_schuur_styrvar_switch' is not loaded
2024-08-25 12:48:43.564965 INFO AppDaemon: Loading app zonnescherm_switch using class E1743CoverController from module controllerx
2024-08-25 12:48:43.565138 WARNING AppDaemon: Unable to find module module controllerx - 'zonnescherm_switch' is not loaded
2024-08-25 12:48:43.565457 INFO AppDaemon: Loading app kerstboom_binnen_styrvar_switch using class E2002LightController from module controllerx
2024-08-25 12:48:43.565628 WARNING AppDaemon: Unable to find module module controllerx - 'kerstboom_binnen_styrvar_switch' is not loaded
2024-08-25 12:48:43.565946 INFO AppDaemon: Loading app zonnescherm_switch_1 using class E1743CoverController from module controllerx
2024-08-25 12:48:43.566126 WARNING AppDaemon: Unable to find module module controllerx - 'zonnescherm_switch_1' is not loaded
2024-08-25 12:48:43.567272 WARNING AppDaemon: Unable to find module Volume_woonkamer - initialize() skipped
2024-08-25 12:48:43.567609 WARNING AppDaemon: Unable to find module Zolder_verlichting_switch - initialize() skipped
2024-08-25 12:48:43.567928 WARNING AppDaemon: Unable to find module Volume_slaapkamer - initialize() skipped
2024-08-25 12:48:43.568241 WARNING AppDaemon: Unable to find module Nachtlampje_rosalie - initialize() skipped
2024-08-25 12:48:43.568497 WARNING AppDaemon: Unable to find module washoek_switch - initialize() skipped
2024-08-25 12:48:43.568789 WARNING AppDaemon: Unable to find module Feestlampen_schuur_styrvar_switch - initialize() skipped
2024-08-25 12:48:43.569060 WARNING AppDaemon: Unable to find module zonnescherm_switch - initialize() skipped
2024-08-25 12:48:43.569323 WARNING AppDaemon: Unable to find module kerstboom_binnen_styrvar_switch - initialize() skipped
2024-08-25 12:48:43.569556 WARNING AppDaemon: Unable to find module zonnescherm_switch_1 - initialize() skipped
2024-08-25 12:49:01.555360 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2024-08-25 12:49:06.565314 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2024-08-25 12:49:11.576554 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2024-08-25 12:49:16.614701 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2024-08-25 12:49:16.742351 WARNING HASS: Error getting services - retrying
Task exception was never retrieved
future: <Task finished name='Task-49804' coro=<HassPlugin.run_hass_service_check() done, defined at /usr/lib/python3.11/site-packages/appdaemon/plugins/hass/hassplugin.py:763> exception=ClientResponseError(RequestInfo(url=URL('http://supervisor/core/api/services'), method='GET', headers=<CIMultiDictProxy('Host': 'supervisor', 'x-ha-access': '80dc885ce11bc84d9d0d809e021ff3c2a06dcefafe3cce56aa29789e5b7519971d1dcf4d6a4be1dfa3c9bb28d9425cfb07c083cf2771b65a', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Python/3.11 aiohttp/3.8.6')>, real_url=URL('http://supervisor/core/api/services')), (), status=502, message='Bad Gateway', headers=<CIMultiDictProxy('Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '16', 'Date': 'Sun, 25 Aug 2024 10:49:16 GMT', 'Server': 'Python/3.12 aiohttp/3.9.5')>)>
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/plugins/hass/hassplugin.py", line 772, in run_hass_service_check
    hass_services = await self.get_hass_services()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/appdaemon/plugins/hass/hassplugin.py", line 732, in get_hass_services
    r.raise_for_status()
  File "/usr/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1011, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 502, message='Bad Gateway', url=URL('http://supervisor/core/api/services')
2024-08-25 12:49:21.627518 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2024-08-25 12:49:26.641530 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2024-08-25 12:49:31.662899 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2024-08-25 12:49:36.678076 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2024-08-25 12:49:41.689930 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2024-08-25 12:49:46.702900 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2024-08-25 12:49:51.710237 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2024-08-25 12:49:56.727084 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2024-08-25 12:50:01.737617 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2024-08-25 12:50:06.770492 INFO HASS: Connected to Home Assistant 2024.8.2
2024-08-25 12:50:06.871442 INFO HASS: Evaluating startup conditions
2024-08-25 12:50:06.876607 INFO HASS: Startup condition met: hass state=RUNNING
2024-08-25 12:50:06.876843 INFO HASS: All startup conditions met
2024-08-25 12:50:06.902467 INFO AppDaemon: Processing restart for HASS
2024-08-25 12:50:06.902886 INFO AppDaemon: Terminating Volume_woonkamer
2024-08-25 12:50:06.903302 INFO AppDaemon: Terminating Zolder_verlichting_switch
2024-08-25 12:50:06.903794 INFO AppDaemon: Terminating Volume_slaapkamer
2024-08-25 12:50:06.904196 INFO AppDaemon: Terminating Nachtlampje_rosalie
2024-08-25 12:50:06.904541 INFO AppDaemon: Terminating washoek_switch
2024-08-25 12:50:06.905025 INFO AppDaemon: Terminating Feestlampen_schuur_styrvar_switch
2024-08-25 12:50:06.905379 INFO AppDaemon: Terminating zonnescherm_switch
2024-08-25 12:50:06.905853 INFO AppDaemon: Terminating kerstboom_binnen_styrvar_switch
2024-08-25 12:50:06.906346 INFO AppDaemon: Terminating zonnescherm_switch_1
2024-08-25 12:50:06.907021 INFO AppDaemon: Loading app Volume_woonkamer using class E1744MediaPlayerController from module controllerx
2024-08-25 12:50:06.907200 WARNING AppDaemon: Unable to find module module controllerx - 'Volume_woonkamer' is not loaded
2024-08-25 12:50:06.907512 INFO AppDaemon: Loading app Zolder_verlichting_switch using class W2049LightController from module controllerx
2024-08-25 12:50:06.907677 WARNING AppDaemon: Unable to find module module controllerx - 'Zolder_verlichting_switch' is not loaded
2024-08-25 12:50:06.907999 INFO AppDaemon: Loading app Volume_slaapkamer using class E1744MediaPlayerController from module controllerx
2024-08-25 12:50:06.908169 WARNING AppDaemon: Unable to find module module controllerx - 'Volume_slaapkamer' is not loaded
2024-08-25 12:50:06.908478 INFO AppDaemon: Loading app Nachtlampje_rosalie using class E1743Controller from module controllerx
2024-08-25 12:50:06.908651 WARNING AppDaemon: Unable to find module module controllerx - 'Nachtlampje_rosalie' is not loaded
2024-08-25 12:50:06.908983 INFO AppDaemon: Loading app washoek_switch using class E1743Controller from module controllerx
2024-08-25 12:50:06.909149 WARNING AppDaemon: Unable to find module module controllerx - 'washoek_switch' is not loaded
2024-08-25 12:50:06.909461 INFO AppDaemon: Loading app Feestlampen_schuur_styrvar_switch using class E2002LightController from module controllerx
2024-08-25 12:50:06.909627 WARNING AppDaemon: Unable to find module module controllerx - 'Feestlampen_schuur_styrvar_switch' is not loaded
2024-08-25 12:50:06.909970 INFO AppDaemon: Loading app zonnescherm_switch using class E1743CoverController from module controllerx
2024-08-25 12:50:06.910145 WARNING AppDaemon: Unable to find module module controllerx - 'zonnescherm_switch' is not loaded
2024-08-25 12:50:06.910516 INFO AppDaemon: Loading app kerstboom_binnen_styrvar_switch using class E2002LightController from module controllerx
2024-08-25 12:50:06.910672 WARNING AppDaemon: Unable to find module module controllerx - 'kerstboom_binnen_styrvar_switch' is not loaded
2024-08-25 12:50:06.910994 INFO AppDaemon: Loading app zonnescherm_switch_1 using class E1743CoverController from module controllerx
2024-08-25 12:50:06.911175 WARNING AppDaemon: Unable to find module module controllerx - 'zonnescherm_switch_1' is not loaded
2024-08-25 12:50:06.912372 WARNING AppDaemon: Unable to find module Volume_woonkamer - initialize() skipped
2024-08-25 12:50:06.912721 WARNING AppDaemon: Unable to find module Zolder_verlichting_switch - initialize() skipped
2024-08-25 12:50:06.913020 WARNING AppDaemon: Unable to find module Volume_slaapkamer - initialize() skipped
2024-08-25 12:50:06.913318 WARNING AppDaemon: Unable to find module Nachtlampje_rosalie - initialize() skipped
2024-08-25 12:50:06.913601 WARNING AppDaemon: Unable to find module washoek_switch - initialize() skipped
2024-08-25 12:50:06.913887 WARNING AppDaemon: Unable to find module Feestlampen_schuur_styrvar_switch - initialize() skipped
2024-08-25 12:50:06.914129 WARNING AppDaemon: Unable to find module zonnescherm_switch - initialize() skipped
2024-08-25 12:50:06.914362 WARNING AppDaemon: Unable to find module kerstboom_binnen_styrvar_switch - initialize() skipped
2024-08-25 12:50:06.914580 WARNING AppDaemon: Unable to find module zonnescherm_switch_1 - initialize() skipped`

**Comment by Meisteryoda1994** [comment]
maby this is easier to read
<img width="1009" alt="Scherm­afbeelding 2024-08-25 om 12 53 05" src="https://github.com/user-attachments/assets/36447a45-3ff8-4200-9f61-0c0307b588e6">
<img width="1051" alt="Scherm­afbeelding 2024-08-25 om 12 53 15" src="https://github.com/user-attachments/assets/4f43522d-ed69-4eee-be90-a7284f2f06a9">
<img width="1062" alt="Scherm­afbeelding 2024-08-25 om 12 53 25" src="https://github.com/user-attachments/assets/c09b4c47-c032-4f85-a4b7-0ab3cb0d060a">
<img width="1047" alt="Scherm­afbeelding 2024-08-25 om 12 53 34" src="https://github.com/user-attachments/assets/e543ee02-fbe6-4e3f-8dc7-ffde0dedc76a">

**Comment by Meisteryoda1994** [comment]
i fixed it Bly replacing the controllerX folder to the config add-on folder. so I think with the redirection there is a failure somewhere because normally it link to the appdeamon  folder

**Comment by xaviml** [comment]
Correct, it seems that appdaemon is not reading the right folder somehow, and I cannot identify why.

You fixed is a workaround, but if ControllerX gets updated, you will need to copy the folder again.

**Comment by Meisteryoda1994** [comment]
yea the same is the problem with the direction of the apps.yaml.
