### ISSUE TITLE
[BUG] IKEA E1743 not working

### ISSUE THREAD

**Issue by carstenriisbjerg** [xaviml/controllerx#1080]
# E1743 unable to dim light up/down

## Description

When holding button up/down the light does not dim up og down. Short press on/off working fine.
This is a new installation of home assistant. And I have another IKEA E1743 switch working fine. Am I
doing something wrong, do I need to reset the IKEA E1743 before using it in a new installation? 

## Additional information

- Devices involved:
  - Controller: IKEA E1743 as Light
  - Light: IKEA NYMANE PENDANT
- Integration: z2m
- AppDaemon version:  v4.4.2
- ControllerX version: V4.28.0
- HACS version (if installed from there): V2.0.1
- Home Assistant Core version: 2024.11.1

## AppDaemon app configuration

```yaml
Lys_Lucas:
  module: controllerx
  class: E1743Controller
  controller: sensor.0x84ba20fffe732baa_action
  integration: z2m
  light: light.0x2c1165fffe03ba7e
```

## Logs

```text
2024-11-10 16:33:43.928540 INFO Lys_Lucas: 🎮 Button event triggered: `on`
2024-11-10 16:33:43.938134 INFO Lys_Lucas: 🏃 Running `Predefined (on)` now
2024-11-10 16:33:43.940997 INFO Lys_Lucas: 
🤖 Service: light.turn_on
  - entity_id: light.0x2c1165fffe03ba7e
2024-11-10 16:33:46.647177 INFO Lys_Lucas: 🎮 Button event triggered: `brightness_move_down`
2024-11-10 16:33:46.651664 INFO Lys_Lucas: 🏃 Running `Predefined (hold_brightness_down)` now
2024-11-10 16:33:46.665150 WARNING Lys_Lucas: ------------------------------------------------------------
2024-11-10 16:33:46.667597 WARNING Lys_Lucas: Unexpected error in worker for App Lys_Lucas:
2024-11-10 16:33:46.667712 WARNING Lys_Lucas: Worker Ags: {'id': '6f84d498a8e24c8fbfe367485ae245e5', 'name': 'Lys_Lucas', 'objectid': 'cda25774276f4aad8c4018dafdf417c6', 'type': 'state', 'function': <bound method Z2MIntegration.state_callback of <cx_core.integration.z2m.Z2MIntegration object at 0x7fccad559810>>, 'attribute': 'state', 'entity': 'sensor.0x84ba20fffe732baa_action', 'new_state': 'brightness_move_down', 'old_state': '', 'pin_app': True, 'pin_thread': 2, 'kwargs': {'__thread_id': 'MainThread'}}
2024-11-10 16:33:46.667776 WARNING Lys_Lucas: ------------------------------------------------------------
2024-11-10 16:33:46.669493 WARNING Lys_Lucas: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/threading.py", line 916, in async_worker
    await funcref(
  File "/homeassistant/appdaemon/apps/controllerx/cx_core/integration/z2m.py", line 71, in state_callback
    await self.controller.handle_action(new, previous_state=old)
  File "/homeassistant/appdaemon/apps/controllerx/cx_core/controller.py", line 399, in handle_action
    await self.call_action(action_key, extra=extra)
  File "/homeassistant/appdaemon/apps/controllerx/cx_core/controller.py", line 473, in call_action
    await self.action_timer_callback({"action_key": action_key, "extra": extra})
  File "/homeassistant/appdaemon/apps/controllerx/cx_core/controller.py", line 511, in action_timer_callback
    await task
  File "/homeassistant/appdaemon/apps/controllerx/cx_core/controller.py", line 527, in call_action_types
    await action_type.run(extra=extra)
  File "/homeassistant/appdaemon/apps/controllerx/cx_core/action_type/predefined_action_type.py", line 118, in run
    await action(*positional, **action_args)
  File "/homeassistant/appdaemon/apps/controllerx/cx_core/controller.py", line 57, in _action_impl
    await method(controller, *args, **kwargs)
  File "/homeassistant/appdaemon/apps/controllerx/cx_core/type/light_controller.py", line 849, in hold
    await self._hold(attribute, direction, mode, steps)
  File "/homeassistant/appdaemon/apps/controllerx/cx_core/type/light_controller.py", line 872, in _hold
    self.value_attribute = await self.get_value_attribute(attribute)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homeassistant/appdaemon/apps/controllerx/cx_core/type/light_controller.py", line 755, in get_value_attribute
    raise ValueError(
ValueError: Value for `brightness` attribute could not be retrieved from `light.0x2c1165fffe03ba7e`. Check the FAQ to know more about this error: https://xaviml.github.io/controllerx/faq
2024-11-10 16:33:46.669590 WARNING Lys_Lucas: ------------------------------------------------------------
2024-11-10 16:33:47.415696 INFO Lys_Lucas: 🎮 Button event triggered: `brightness_stop`
2024-11-10 16:33:47.420024 INFO Lys_Lucas: 🏃 Running `Predefined (release)` now
```

## Additional Context

Add any other context or screenshots about the bug here.

**Comment by xaviml** [comment]
Hi @carstenriisbjerg ,

The problem is not the controller but the light. It says that the light does not have the attribute brightness in its state.

You can check whether the attribute "brightness" is shown in the state attributes from the "Developer Tools > States".

I have seen this issue when the light is connected for the first time, so try to change brightness from Home Assistant first and then try again with the controller.

Regards,
Xavi M.

**Comment by carstenriisbjerg** [comment]
Thank you, that fixed it...

Best Regards
Carsten

**Comment by RogerSh** [comment]
I have a similar problem. Tested with MiDeskLampPro which has a 'brightness' attribute. Dimmer used to work then stopped recently. Adjusting brightness upwards with HA makes the button work to brighten. Gets stuck after 100% reached. Down brightness does not work at all.
I can see 'Running `Predefined (hold_brightness_up)` now' in the log but never a down equivalent.
Same issue with a light group of mixed devices.

**Comment by xaviml** [comment]
Closing this ticket for now. @RogerSh , if you still have this issue, please create a new ticket fullfiling the form. Thanks!
