### ISSUE TITLE
[BUG] IKEA 1743 as CallServiceController

### ISSUE THREAD

**Issue by Aledan862** [xaviml/controllerx#112]
# Bug report

## Description

Previously fully working automation after recent updates throws an error

## Additional information

* Devices involved:
  * Model:  `IKEA 1743` as `CallServiceController`
* Integration: `z2m`
* AppDaemon version: `v4.0.3`
* ControllerX version: `v3.4.0b1`
* HACS version (if installed from there): `1.3.3`
* Home Assistant Core version: `0.114.0`

## AppDaemon app configuration

```yaml
sergey_room:
  module: controllerx
  class: E1743Controller
  controller: sensor.0x14b457fffe7b9c35_click
  integration: z2m
  light: light.komnata_sergeia_zgroup
  excluded_actions: ["on"]
  
sergey_room_on:
  module: controllerx
  class: CallServiceController
  controller: sensor.0x14b457fffe7b9c35_click
  integration: z2m
  mapping:
    "on": # Give an action to `on` with CallServiceController
      service: light.turn_on
      data:
        entity_id: light.komnata_sergeia_zgroup
        brightness: 255
```

## Logs

```
2020-08-13 19:51:37.676259 WARNING sergey_room_on: ------------------------------------------------------------
2020-08-13 19:51:37.675169 WARNING sergey_room_on: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 709, in async_worker
    await funcref(entity, attr, old_state, new_state, self.AD.state.sanitize_state_kwargs(app, args["kwargs"]))
  File "/config/appdaemon/apps/controllerx/cx_core/integration/z2m.py", line 22, in state_callback
    listens_to = self.kwargs.get("listen_to", LISTENS_TO_HA)
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 144, in handle_action
    def get_list(self, entities: Union[Sequence[str], str]) -> List[str]:
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 162, in call_action
    f"  - {attribute}: {value}", level="INFO", ascii_encode=False,
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 173, in action_timer_callback
    f"🎮 Button event triggered: `{action_key}`",
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 234, in _action_impl
    if isinstance(action, str):
  File "/config/appdaemon/apps/controllerx/cx_core/custom_controller.py", line 76, in call_services
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 120, in call_service
    f"Type {type(integration)} is not supported for `integration` attribute"
  File "/usr/lib/python3.8/site-packages/appdaemon/adapi.py", line 143, in log
    msg = self._sub_stack(msg)
  File "/usr/lib/python3.8/site-packages/appdaemon/adapi.py", line 56, in _sub_stack
    stack = inspect.stack()
  File "/usr/lib/python3.8/inspect.py", line 1514, in stack
    return getouterframes(sys._getframe(1), context)
  File "/usr/lib/python3.8/inspect.py", line 1491, in getouterframes
    frameinfo = (frame,) + getframeinfo(frame, context)
  File "/usr/lib/python3.8/inspect.py", line 1465, in getframeinfo
    lines, lnum = findsource(frame)
  File "/usr/lib/python3.8/inspect.py", line 840, in findsource
    if pat.match(lines[lnum]): break
IndexError: list index out of range

2020-08-13 19:51:37.673376 WARNING sergey_room_on: ------------------------------------------------------------
2020-08-13 19:51:37.672246 WARNING sergey_room_on: Worker Ags: {'id': 'abcc246fa18346409f0ea818bfbc56dd', 'name': 'sergey_room_on', 'objectid': '908da0b2e5614d04b7acdd4b5113afb8', 'type': 'state', 'function': >, 'attribute': 'state', 'entity': 'sensor.0x14b457fffe7b9c35_click', 'new_state': 'on', 'old_state': '', 'pin_app': True, 'pin_thread': 1, 'kwargs': {'__thread_id': 'MainThread'}}
2020-08-13 19:51:37.670339 WARNING sergey_room_on: Unexpected error in worker for App sergey_room_on:
2020-08-13 19:51:37.668828 WARNING sergey_room_on: ------------------------------------------------------------
```

**Comment by xaviml** [comment]
Hi @Aledan862,

Thank you for trying out the beta version. I appreciate that people tries it out before I do an stable release.

However, by looking at the errors, the shown lines do not match with the lines from v3.4.0b1 code. Did you restart the AppDaemon server after updating ControllerX? If not, could you try to restart and see if error still persists?

Thank you,
Xavi M.

**Comment by Aledan862** [comment]
Sorry, for the long answer. I reinstalled the ControllerX app and rebooted the AppDaemon addon. And an error is gone.
