### ISSUE TITLE
Problem with deconz and IKEA E1743

### ISSUE THREAD

**Issue by fribse** [xaviml/controllerx#16]
Controllerx: 2.0.0
HA: 0.104.3
Deconz: 5.1

I have connected two E1810 controllers without problems.
Now I want to add a E1743 controller, but it doesn't work.
As I understand it, the E1743 is the small square one with 'I' and 'O' printed on it.

The app I've created for this looks like this:

bathroom:
  module: controllerx
  class: E1743Controller
  event_id: bathroom_dimmer
  light: light.bathroom_mirror

If I move one of the E1810 controllers to this, then it works.
I actually need it to control a group, but for simplicity, I've changed it to a single light.

**Comment by xaviml** [comment]
Hi @fribse,

If you check the logs you are probably seeing the following message: 
`This controller does not support event actions.`

This is because E1743 does not have the event mapping defined in the v2.0.0. I close a PR recently of someone defining the event mapping for this controller. The code is still on the master branch and it will be shipped on the next release. I will release some time this weekend.

If this error is not the one that appears in your logs, please copy & paste the errors you see.

Thanks

**Comment by fribse** [comment]
@xaviml Thankyou very much for a quick reply (lightning fast actually :-) ).
Where do I find the logfile for this app?

**Comment by xaviml** [comment]
How do you run appdaemon? If you run it with the hassio addon, you can go to the hassio addon and at the end you will find the logs @fribse

**Comment by fribse** [comment]
Ahh 😊 I thought it had it's own log, you are right, I see this in the log:

```
2020-01-25 09:57:43.322479 INFO AppDaemon: Initializing app bathroom using class E1743Controller from module controllerx
2020-01-25 09:57:43.331040 WARNING bathroom: ------------------------------------------------------------
2020-01-25 09:57:43.331958 WARNING bathroom: Unexpected error running initialize() for bathroom
2020-01-25 09:57:43.332842 WARNING bathroom: ------------------------------------------------------------
2020-01-25 09:57:43.334014 WARNING bathroom: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 145, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 276, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/appdaemon/apps/controllerx/controllerx.py", line 268, in initialize
    super().initialize()
  File "/config/appdaemon/apps/controllerx/controllerx.py", line 161, in initialize
    super().initialize()
  File "/config/appdaemon/apps/controllerx/controllerx.py", line 64, in initialize
    raise ValueError(
ValueError: This controller does not support event actions.
```

**Comment by xaviml** [comment]
I will let you know when I release the code, so you can download it. You can also change to `master` on HACS.

**Comment by fribse** [comment]
Well, I have to take care of the WAF as well, so I'll stay with the released code, just in case a bug is found in the last second 😄 
Thankyou for clearing up the issue.

**Comment by fribse** [comment]
Any news on the release 😄 ?

**Comment by xaviml** [comment]
Hi @fribse 

I just released the latest code, it includes the mapping for the E1743 for deCONZ. I hope you enjoy it!
Closing the issue.

**Comment by fribse** [comment]
Hi @xaviml 
THANKYOU, I've updated the app. It reacts very nicely on the remote now, unfortuncaly the buttons are reversed 😆
