### ISSUE TITLE
HueDimmerController needs Light

### ISSUE THREAD

**Issue by Dougiebabe** [xaviml/controllerx#179]
Hello and I apologise if this is me being dumb but I have tried to get this working for a few evenings now and hit a road block each time. I'll try and provide as much information as I can but feel free to request more info,

Home Assistant Version: 0.117.5
AppDaemon4 Version: 0.3.1
ControllerX Version: 4.1 (Installed via HACS)

So I have controllerX working fine for standard switches on lights without issue and also have a CustomLightController setup for a hallway light without issue.

The problem I am facing is that I want to customise the HueDimmerController I have in the living room. I want the HueDimmer to control the lights normally but remove the 'On-Hold' mapping and use that to set the living scene to 'scene.normal_lounge'

Here is the config I use to control the Living Room lights normally
```
livingroom_hue_dimmer:
  module: controllerx
  class: HueDimmerController
  controller: sensor.switchloungehuedimmer_action
  integration: z2m
  light: light.living_room_lights
```

To help troubleshoot the issue I am substituting 'On-Hold' for 'Up-press' and not calling the scene service but replaced with notify service. I am following these instructions [here](https://xaviml.github.io/controllerx/others/custom-controllers) right at the bottom of the page.

Here is the config that is not working:
```
livingroom_hue_dimmer:
  module: controllerx
  class: HueDimmerController
  controller: sensor.switchloungehuedimmer_action
  integration: z2m
  light: light.living_room_lights
  actions:
    - on-press
    - off-press
#    - up-press
    - up-hold
    - up-hold-release
    - down-press
    - down-hold
    - down-hold-release
    - off-press
    - off-hold
    - off-hold-release



livingroom_hue_dimmer_Scene:
  module: controllerx
  class: HueDimmerController
  controller: sensor.switchloungehuedimmer_action
  integration: z2m
  mapping:
    up-press:
      - service: notify.mobile_app_dougs_note
        data:
          message: "This is a test"
 ```

The output from the log:

```
2020-11-20 21:33:06.384001 INFO AppDaemon: Initializing app livingroom_hue_dimmer_Scene using class HueDimmerController from module controllerx
2020-11-20 21:33:06.386346 WARNING livingroom_hue_dimmer_Scene: ------------------------------------------------------------
2020-11-20 21:33:06.386628 WARNING livingroom_hue_dimmer_Scene: Unexpected error running initialize() for livingroom_hue_dimmer_Scene
2020-11-20 21:33:06.386885 WARNING livingroom_hue_dimmer_Scene: ------------------------------------------------------------
2020-11-20 21:33:06.387345 WARNING livingroom_hue_dimmer_Scene: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 148, in initialize_app
    await init()
  File "/config/appdaemon/apps/controllerx/cx_core/type/light_controller.py", line 53, in initialize
    self.light = self.get_light(self.args["light"])
KeyError: 'light'
```

The issue is if I put a light in the app then it will control the light fully including the 'up-press' which has the mapping. It seems that the HueDimmerController requires the use of a 'Light' even though the documentation shows that I should be able to call a service with this controller class.

I have also tried changing the controller class to 'Controller' (as I wasn't sure if that allows for custom services to be called) but this controller shows the following error:

```
2020-11-20 23:26:38.159531 WARNING livingroom_hue_dimmer_Scene: ------------------------------------------------------------
2020-11-20 23:26:38.159773 WARNING livingroom_hue_dimmer_Scene: Unexpected error running initialize() for livingroom_hue_dimmer_Scene
2020-11-20 23:26:38.159958 WARNING livingroom_hue_dimmer_Scene: ------------------------------------------------------------
2020-11-20 23:26:38.160281 WARNING livingroom_hue_dimmer_Scene: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 148, in initialize_app
    await init()
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 33, in initialize
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 108, in get_actions_mapping
    )
ValueError: This controller does not support z2m.
```

I have also tried the following configuration but this just controlled the light as normal and ignored the custom mappings:

```
livingroom_hue_dimmer:
  module: controllerx
  class: HueDimmerController
  controller: sensor.switchloungehuedimmer_action
  integration: z2m
  light: light.living_room_lights
  mapping:
    on-press: on
    on-hold:
      - service: notify.mobile_app_dougs_note
        data:
          message: "this is a test"
    off-press: off
    up-press: click_brightness_up
    up-hold: hold_brightness_up
    up-hold-release: release
    down-press: click_brightness_down
    down-hold: hold_brightness_down
    down-hold-release: release
    off-hold: on_full_brightness
    off-hold-release: release
```

**Comment by xaviml** [comment]
Hi @Dougiebabe,

It seems you have tried lots of options, I am still confused why some of them don't work. First of all, the `HueDimmerController` class is a Light controller class (you can see that in [here](https://xaviml.github.io/controllerx/controllers/hue-dimmer-switch)). This means that the class needs a `light` parameter to be passed. This is the reason is complaining. However, I see you also tried to change the `HueDimmerController` for just `Controller` and you got `ValueError: This controller does not support z2m.`. For this case, did you have the `mapping` attribute?

There are different ways to solve this problem, and I see you attempt some of them and you are claiming they are not working and that is what confuses me. Let's do the following, let me tell you how I would solve the problem you are having in a much cleaner way and if you have errors in the configuration or it is not working as expected, could you send the logs in here?

```yaml
livingroom_hue_dimmer:
  module: controllerx
  class: HueDimmerController
  controller: sensor.switchloungehuedimmer_action
  integration: z2m
  light: light.living_room_lights
  merge_mapping:
    up-press:
      service: notify.mobile_app_dougs_note
      data:
        message: "this is a test"
```

The `merge_mapping` will keep the default mapping, but overwrite the ones you define (in this case `up-press`). So when pressing up (the "I" button), it should send a notification to your phone. If that is not what is happening, could you paste the logs in here for when you press the button? Could you also paste the Zigbee2MQTT logs so I see which actions are fired from Zigbee2MQTT?

Cheers,
Xavi M.

**Comment by Dougiebabe** [comment]
Hi Xavi,

So I assumed the HueDimmerController was a Light Controller and was causing the issue for a light entity to be required but was confused by the last section of the custom controller where you have specified the same controller, HueDimmerController, and used custom services.

I hadn't tried what you have suggested above and have just tried it but am still seeing the same response from the controller, even with a merge_mapping specified it still only controls the lights and ignores the custom service

Config extract:

'''
livingroom_hue_dimmer:
  module: controllerx
  class: HueDimmerController
  controller: sensor.switchloungehuedimmer_action
  integration: z2m
  light: light.living_room_lights
  merge_mapping:
  up-press:
    service: notify.mobile_app_dougs_note
    data:
      message: "this is a test"
'''


Appdaemon Log:

'''
2020-11-24 21:45:09.031822 INFO AppDaemon: Initializing app livingroom_hue_dimmer using class HueDimmerController from module controllerx
2020-11-24 21:45:09.035850 INFO bedroom_side_lights_controller: 🎮 ControllerX v3.3.0
2020-11-24 21:45:09.049313 INFO bedroom_festoon_controller: 🎮 ControllerX v3.3.0
2020-11-24 21:45:09.053222 INFO landing_controller: 🎮 ControllerX v3.3.0
2020-11-24 21:45:09.056491 INFO livingroom_hue_dimmer: 🎮 ControllerX v3.3.0
2020-11-24 21:45:14.731861 INFO livingroom_hue_dimmer: 🎮 Button event triggered: `up-press`
2020-11-24 21:45:14.734937 INFO livingroom_hue_dimmer: 🏃 Running `click_brightness_up` now
2020-11-24 21:45:14.739889 INFO livingroom_hue_dimmer: 🤖 Service: light.turn_on
2020-11-24 21:45:14.743011 INFO livingroom_hue_dimmer:   - entity_id: light.living_room_lights
2020-11-24 21:45:14.746165 INFO livingroom_hue_dimmer:   - brightness: 222.30
2020-11-24 21:45:14.756083 INFO livingroom_hue_dimmer:   - transition: 0.30
2020-11-24 21:45:17.562633 INFO livingroom_hue_dimmer: 🎮 Button event triggered: `up-press`
2020-11-24 21:45:17.564460 INFO livingroom_hue_dimmer: 🏃 Running `click_brightness_up` now
2020-11-24 21:45:17.569242 INFO livingroom_hue_dimmer: 🤖 Service: light.turn_on
2020-11-24 21:45:17.573425 INFO livingroom_hue_dimmer:   - entity_id: light.living_room_lights
2020-11-24 21:45:17.576413 INFO livingroom_hue_dimmer:   - brightness: 246.30
2020-11-24 21:45:17.579367 INFO livingroom_hue_dimmer:   - transition: 0.30
'''

Zigbee2MQTT log:

'''
Zigbee2MQTT:info  2020-11-24 20:48:05: MQTT publish: topic 'zigbee2mqtt/Switch-Lounge-HueDimmer', payload '{"action":"up-press","battery":100,"brightness":193,"counter":1,"duration":0,"linkquality":94,"update_available":false}'
Zigbee2MQTT:info  2020-11-24 20:48:05: MQTT publish: topic 'zigbee2mqtt/Switch-Lounge-HueDimmer', payload '{"action":"","battery":100,"brightness":193,"counter":1,"linkquality":94,"update_available":false}'
Zigbee2MQTT:info  2020-11-24 20:48:05: MQTT publish: topic 'zigbee2mqtt/Switch-Lounge-HueDimmer/action', payload 'up-press'
'''


I also tried the following config but this gave me the same error:

'''
livingroom_hue_dimmer:
  module: controllerx
  class: Controller
  controller: sensor.switchloungehuedimmer_action
  integration: z2m
  light: light.living_room_lights
  mapping:
    - on-press
    - off-press
    - up-press
    - up-hold
    - up-hold-release
    - down-press
    - down-hold
    - down-hold-release
    - off-press
    - off-hold
    - off-hold-release
'''

AppDaemon log:

'''
2020-11-24 21:49:55.768106 INFO AppDaemon: Initializing app livingroom_hue_dimmer using class Controller from module controllerx
2020-11-24 21:49:55.772321 INFO livingroom_hue_dimmer: 🎮 ControllerX v3.3.0
2020-11-24 21:49:55.772983 WARNING livingroom_hue_dimmer: ------------------------------------------------------------
2020-11-24 21:49:55.773208 WARNING livingroom_hue_dimmer: Unexpected error running initialize() for livingroom_hue_dimmer
2020-11-24 21:49:55.773409 WARNING livingroom_hue_dimmer: ------------------------------------------------------------
2020-11-24 21:49:55.773705 WARNING livingroom_hue_dimmer: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 148, in initialize_app
    await init()
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 33, in initialize
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 108, in get_actions_mapping
    )
ValueError: This controller does not support z2m.

2020-11-24 21:49:55.773960 WARNING livingroom_hue_dimmer: ------------------------------------------------------------
'''

Let me know if there is anything you need me to try and I'll give it a go.

Cheers,

Doug

**Comment by xaviml** [comment]
Hi @Dougiebabe,

The merge mapping is new from ControllerX v4.0.0. You mentioned you have installed v4.1.0 from HACS but I see from logs you are using v3.3.0.

What probably happened is that you did not restart the addon after updating ControllerX. AppDaemon needs to be restarted everytime you want to use a different version of ControllerX.

Try to restart AppDaemon and check logs again.

Regards,
Xavi M.

**Comment by Dougiebabe** [comment]
Hi Xavi,

And just like that it is working! I had restarted Home Assistant multiple times since upgrading and did just a minute ago but it seems that AppDaemon itself does indeed need a separate restart.

I used the config you posted above for clarity. I still had the Class: Controller in place from testing earlier and this time it said Attribute: List missing or something like that and not z2m is not supported so I would assume that would work if I fixed the mapping/attributes.

Thank you very much for the assistance and for making this wonderful add-on!

Kind Regards,

Doug

**Comment by xaviml** [comment]
Hi Doug,

I am glad you got it working. I have to say that the example from the documentation you screenshot is wrong and outdated. You can see that is useing HueDimmerController without a "light". I will simplify the example to just use one confg with `merge_mapping`. So, sorry if that example confused you.

Regards,
Xavi M.
