### ISSUE TITLE
[BUG] Error when starting 4.2.0

### ISSUE THREAD

**Issue by fribse** [xaviml/controllerx#188]
# Bug report

## Description

When I upgrade to 4.2.0 I see this in the logs, and controllerx doesn't seem to work. I don't see any errors or warnings on 4.1.0
Not sure what causes it.

## Additional information

* Devices involved:
  * Model: Not sture
  * ...
* Integration: deconz
* AppDaemon version: 0.3.2
* ControllerX version: 4.2.0
* HACS version: 1.6.2
* Home Assistant Core version: 0.118.4

## AppDaemon app configuration

Not sure.
The devices I have are primarily IKEA and Aqara, but posting the entire config seems problematic.

## Logs

```text
2020-11-29 09:42:52.551731 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/controllerx/controllerx.py
2020-11-29 09:42:52.560766 WARNING Error: ------------------------------------------------------------
2020-11-29 09:42:52.561655 WARNING Error: Unexpected error loading module: /config/appdaemon/apps/controllerx/controllerx.py:
2020-11-29 09:42:52.562312 WARNING Error: ------------------------------------------------------------
2020-11-29 09:42:52.563868 WARNING Error: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 875, in check_app_updates
    await utils.run_in_executor(self, self.read_app, mod["name"], mod["reload"])
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 290, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 671, in read_app
    importlib.reload(self.modules[module_name])
  File "/usr/lib/python3.8/importlib/__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 604, in _exec
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/appdaemon/apps/controllerx/controllerx.py", line 26, in <module>
    from cx_devices.sonoff import *
  File "/config/appdaemon/apps/controllerx/cx_devices/sonoff.py", line 3, in <module>
    from cx_core.integration import EventData
ImportError: cannot import name 'EventData' from 'cx_core.integration' (/config/appdaemon/apps/controllerx/cx_core/integration/__init__.py)
2020-11-29 09:42:52.567065 WARNING Error: ------------------------------------------------------------
```

## Additional Context

From the 4.1.0 startup log:

```text
2020-11-29 09:48:00.220258 INFO AppDaemon: Initializing app adrians_skrivebord using class E1810Controller from module controllerx
2020-11-29 09:48:00.223231 INFO AppDaemon: Initializing app adrians_loftlys using class E1810Controller from module controllerx
2020-11-29 09:48:00.225447 INFO AppDaemon: Initializing app bathroom using class E1743Controller from module controllerx
2020-11-29 09:48:00.227581 INFO AppDaemon: Initializing app kenneths_skrivebord using class E1810Controller from module controllerx
2020-11-29 09:48:00.229819 INFO AppDaemon: Initializing app kitchen_dinnertable using class E1810Controller from module controllerx
2020-11-29 09:48:00.231970 INFO AppDaemon: Initializing app lians_magic_cube1 using class MFKZQ01LMLightController from module controllerx
2020-11-29 09:48:00.234366 INFO AppDaemon: Initializing app nathalie_ceiling using class E1810Controller from module controllerx
2020-11-29 09:48:00.236492 INFO AppDaemon: Initializing app livingroom1 using class E1810Controller from module controllerx
2020-11-29 09:48:00.238943 INFO AppDaemon: Initializing app livingroom2 using class E1810Controller from module controllerx
2020-11-29 09:48:00.241051 INFO AppDaemon: Initializing app livingroom3 using class E1743Controller from module controllerx
2020-11-29 09:48:00.243266 INFO AppDaemon: Initializing app Hallway1 using class E1743Controller from module controllerx
2020-11-29 09:48:00.245700 INFO AppDaemon: Initializing app Hallway2 using class E1743Controller from module controllerx
2020-11-29 09:48:00.247911 INFO AppDaemon: Initializing app Stairs-botton using class E1743Controller from module controllerx
2020-11-29 09:48:00.250015 INFO AppDaemon: Initializing app Stairs-top using class E1743Controller from module controllerx
2020-11-29 09:48:00.257996 INFO adrians_skrivebord: 🎮 ControllerX v4.1.0
2020-11-29 09:48:00.262959 INFO adrians_loftlys: 🎮 ControllerX v4.1.0
2020-11-29 09:48:00.267730 INFO bathroom: 🎮 ControllerX v4.1.0
2020-11-29 09:48:00.273775 INFO kenneths_skrivebord: 🎮 ControllerX v4.1.0
2020-11-29 09:48:00.278737 INFO kitchen_dinnertable: 🎮 ControllerX v4.1.0
2020-11-29 09:48:00.283450 INFO lians_magic_cube1: 🎮 ControllerX v4.1.0
2020-11-29 09:48:00.288394 INFO nathalie_ceiling: 🎮 ControllerX v4.1.0
2020-11-29 09:48:00.293557 INFO livingroom1: 🎮 ControllerX v4.1.0
2020-11-29 09:48:00.298608 INFO livingroom2: 🎮 ControllerX v4.1.0
2020-11-29 09:48:00.303459 INFO livingroom3: 🎮 ControllerX v4.1.0
2020-11-29 09:48:00.308602 INFO Hallway1: 🎮 ControllerX v4.1.0
2020-11-29 09:48:00.313321 INFO Hallway2: 🎮 ControllerX v4.1.0
2020-11-29 09:48:00.318172 INFO Stairs-botton: 🎮 ControllerX v4.1.0
2020-11-29 09:48:00.323291 INFO Stairs-top: 🎮 ControllerX v4.1.0
```

**Comment by xaviml** [comment]
Hi @fribse,

Thank you for reporting the bug. Have you restarted the AppDaemon after updating ControllerX from HACS?

I get the exact same error when not restarting AppDaemon.

Regards,
Xavi M.

**Comment by fribse** [comment]
Hi Xavi
You are absolutely right! Wow that was fast :-D
A restart of appdaemon cleared the message, and it works as it should now :-)
Thankyou for the fast response!

**Comment by xaviml** [comment]
No worries! I will try to work in a way to show a meaningful message for this problem.

Every time ControllerX is updated, AppDaemon needs to be updated.
