### ISSUE TITLE
[QUESTION] Problem running automation - toggle (change) devices doesn't work as expected.

### ISSUE THREAD

**Issue by broda1125** [xaviml/controllerx#233]
# Question

Hello. Following other issue I was trying to use Aqara Cube to control two different lights using "slide" action to swap between these. I've created input_select with two options (for each light: male & duze) and excluded "slide" action but still facing errors in log and lights are not changing. What I am doing wrong here?

## Additional information

* Devices involved:
  * Model: Xiaomi Cube (Aqara) as Light controller
  * ...
* Integration:   zha
* AppDaemon version: 4.0.5
* ControllerX version: 4.5.0
* HACS version (if installed from there): 1.10.1
* Home Assistant Core version: 2021.1.5

## AppDaemon app configuration

select_light_app:
  module: controllerx
  class: Controller
  controller: 00:15:8d:00:05:4b:87:37
  integration: zha
  mapping:
    slide:
      service: input_select.select_next
      data:
        entity_id: input_select.swiatla
light_app_1:
  module: controllerx
  class: MFKZQ01LMLightController
  controller: 00:15:8d:00:05:4b:87:37
  integration: zha
  light: light.male
  constrain_input_select: input_select.swiatla,male
  excluded_actions: slide
light_app_2:
  module: controllerx
  class: MFKZQ01LMLightController
  controller: 00:15:8d:00:05:4b:87:37
  integration: zha
  light: light.duze
  constrain_input_select: input_select.swiatla,duze
  excluded_actions: slide

## Logs

2021-01-26 00:00:39.836978 WARNING select_light_app: ------------------------------------------------------------
2021-01-26 00:00:39.836176 WARNING select_light_app: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 838, in async_worker
    await funcref(args["event"], data, self.AD.events.sanitize_event_kwargs(app, args["kwargs"]))
  File "/config/appdaemon/apps/controllerx/cx_core/integration/zha.py", line 36, in callback
    action = self.get_action(data)
  File "/config/appdaemon/apps/controllerx/cx_core/integration/zha.py", line 23, in get_action
    args = args["args"]
KeyError: 'args'

2021-01-26 00:00:39.834965 WARNING select_light_app: ------------------------------------------------------------
2021-01-26 00:00:39.834228 WARNING select_light_app: Worker Ags: {'id': '499287a7c29942cda7e732a902b53bb5', 'name': 'select_light_app', 'objectid': 'd1ac0c9bfce04fd7ba21cf4b82ce018f', 'type': 'event', 'event': 'zha_event', 'function': >, 'data': {'device_ieee': '00:15:8d:00:05:4b:87:37', 'unique_id': '00:15:8d:00:05:4b:87:37:2:0x0012', 'device_id': 'a52d360597c184525643f9d77a330e36', 'endpoint_id': 2, 'cluster_id': 18, 'command': 'slide', 'args': {'value': 257.0, 'description': 'aqara logo facing user rotated 90 degrees right', 'activated_face': 2}}, 'pin_app': True, 'pin_thread': 0, 'kwargs': {'device_ieee': '00:15:8d:00:05:4b:87:37', '__thread_id': 'MainThread'}}
2021-01-26 00:00:39.833087 WARNING select_light_app: Unexpected error in worker for App select_light_app:
2021-01-26 00:00:39.832141 WARNING select_light_app: ------------------------------------------------------------
2021-01-26 00:00:35.616805 WARNING select_light_app: ------------------------------------------------------------
2021-01-26 00:00:35.616069 WARNING select_light_app: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 838, in async_worker
    await funcref(args["event"], data, self.AD.events.sanitize_event_kwargs(app, args["kwargs"]))
  File "/config/appdaemon/apps/controllerx/cx_core/integration/zha.py", line 36, in callback
    action = self.get_action(data)
  File "/config/appdaemon/apps/controllerx/cx_core/integration/zha.py", line 23, in get_action
    args = args["args"]
KeyError: 'args'

2021-01-26 00:00:35.614631 WARNING select_light_app: ------------------------------------------------------------
2021-01-26 00:00:35.613759 WARNING select_light_app: Worker Ags: {'id': '499287a7c29942cda7e732a902b53bb5', 'name': 'select_light_app', 'objectid': 'd1ac0c9bfce04fd7ba21cf4b82ce018f', 'type': 'event', 'event': 'zha_event', 'function': >, 'data': {'device_ieee': '00:15:8d:00:05:4b:87:37', 'unique_id': '00:15:8d:00:05:4b:87:37:3:0x000c', 'device_id': 'a52d360597c184525643f9d77a330e36', 'endpoint_id': 3, 'cluster_id': 12, 'command': 'rotate_right', 'args': {'relative_degrees': 59.57999038696289}}, 'pin_app': True, 'pin_thread': 0, 'kwargs': {'device_ieee': '00:15:8d:00:05:4b:87:37', '__thread_id': 'MainThread'}}
2021-01-26 00:00:35.612352 WARNING select_light_app: Unexpected error in worker for App select_light_app:
2021-01-26 00:00:35.611489 WARNING select_light_app: ------------------------------------------------------------

## Additional Context

Add any other context or screenshots about the question here.

**Comment by xaviml** [comment]
Hi @broda1125,

The problem you are having is coming from this configuration:
```yaml
select_light_app:
  module: controllerx
  class: Controller
  controller: 00:15:8d:00:05:4b:87:37
  integration: zha
  mapping:
    slide:
      service: input_select.select_next
      data:
        entity_id: input_select.swiatla
```

ZHA integration is an especial one, the way the events are fired varies a lot depending on the device. This is why some controllers have a specific parser to extract the actions. This is the case for the Aqara cube, this is why you need to specify the device class (`MFKZQ01LMLightController`) even though you don't need it for any light. So you can change this config to:

```yaml
select_light_app:
  module: controllerx
  class: MFKZQ01LMLightController
  controller: 00:15:8d:00:05:4b:87:37
  integration: zha
  light: light.male
  mapping:
    slide:
      service: input_select.select_next
      data:
        entity_id: input_select.swiatla
```

Ideally, there should be a generic class for each device, but this is something that would be useful for some devices and if using ZHA, this is why this has not been added.

Regards,
Xavi M.

**Comment by broda1125** [comment]
Good evening!

Works like a charm now! Many thanks! Does it mean for ZHA I have to always use proper device class? 

Question answered, can be closed now ;)

**Comment by xaviml** [comment]
I'm glad you got it working! :)

> Does it mean for ZHA I have to always use proper device class?

Not always, but I would recommend it. There is a generic parser that works for most of the devices, however, special device events need a parser for the specific device.
