### ISSUE TITLE
[BUG] Unexpected error running initialize() for cover_control

### ISSUE THREAD

**Issue by ando023** [xaviml/controllerx#275]
# Bug report

## Description

Cover controller failing to initialize and is diverting back to light controller. 

## Additional information

* Devices involved:
  * IKEA E1743 as cover controller
  * Zemismart Blind via Tuya integration in HA
* Integration: zha
* AppDaemon version: v0.5.1
* ControllerX version: v4.10.0
* HACS version (if installed from there): 1.11.3
* Home Assistant Core version: core-2021.3.4

## AppDaemon app configuration

```yaml
cover_control:
  module: controllerx
  class: E1743Controller
  controller: cc:cc:cc:cc:cc:cc:cc:cc
  integration: zha
  cover: cover.abcd
```

## Logs

```text
2021-04-10 19:57:09.521345 INFO cover_control: 🎮 ControllerX v4.10.0
2021-04-10 19:57:09.521661 WARNING cover_control: ------------------------------------------------------------
2021-04-10 19:57:09.521853 WARNING cover_control: Unexpected error running initialize() for cover_control
2021-04-10 19:57:09.522074 WARNING cover_control: ------------------------------------------------------------
2021-04-10 19:57:09.522409 WARNING cover_control: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 159, in initialize_app
    await init()
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 101, in initialize
    await self.init()
  File "/config/appdaemon/apps/controllerx/cx_core/type/light_controller.py", line 125, in init
    await super().init()
  File "/config/appdaemon/apps/controllerx/cx_core/type_controller.py", line 30, in init
    raise ValueError(
ValueError: E1743Controller class needs the `light` attribute
2021-04-10 19:57:09.522597 WARNING cover_control: ------------------------------------------------------------
```

**Comment by xaviml** [comment]
Hi @ando023,

You should use the a Cover Controller, so in this case: `E1743CoverController`. Your configuration should look like:

```yaml
cover_control:
  module: controllerx
  class: E1743CoverController
  controller: cc:cc:cc:cc:cc:cc:cc:cc
  integration: zha
  cover: cover.abcd
```

The `E1743Controller` is a light controller. For new controller I place the type in the name, so that controller should be renamed to `E1743LightController`, but this was one of the first controllers, so the naming convention did not exist. I will deprecate this in the future, and change the names to include the type in the class.

Regards,
Xavi M.

**Comment by ando023** [comment]
Ah okay that makes sense. 

All working now. Thank you for your quick response!
