### ISSUE TITLE
[BUG] AttributeError: type object 'Light' has no attribute 'CLICK'

### ISSUE THREAD

**Issue by gumslone** [xaviml/controllerx#344]
## Logs

```text
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/appdaemon/app_management.py", line 159, in initialize_app
    await init()
  File "/conf/apps/controllerx/cx_core/controller.py", line 107, in initialize
    await self.init()
  File "/conf/apps/controllerx/cx_core/type/light_controller.py", line 130, in init
    await super().init()
  File "/conf/apps/controllerx/cx_core/type_controller.py", line 63, in init
    await super().init()
  File "/conf/apps/controllerx/cx_core/release_hold_controller.py", line 18, in init
    await super().init()
  File "/conf/apps/controllerx/cx_core/controller.py", line 121, in init
    self.actions_mapping = self.parse_action_mapping(default_actions_mapping)  # type: ignore
  File "/conf/apps/controllerx/cx_core/controller.py", line 255, in parse_action_mapping
    return {event: parse_actions(self, action) for event, action in mapping.items()}
  File "/conf/apps/controllerx/cx_core/controller.py", line 255, in 
    return {event: parse_actions(self, action) for event, action in mapping.items()}
  File "/conf/apps/controllerx/cx_core/action_type/__init__.py", line 30, in parse_actions
    return [_parse_action(controller, action) for action in actions]
  File "/conf/apps/controllerx/cx_core/action_type/__init__.py", line 30, in 
    return [_parse_action(controller, action) for action in actions]
  File "/conf/apps/controllerx/cx_core/action_type/__init__.py", line 35, in _parse_action
    return PredefinedActionType(controller, {"action": action})
  File "/conf/apps/controllerx/cx_core/action_type/base.py", line 15, in __init__
    self.initialize(**action)
  File "/conf/apps/controllerx/cx_core/action_type/predefined_action_type.py", line 94, in initialize
    self.controller.get_predefined_actions_mapping()
  File "/conf/apps/controllerx/cx_core/type/light_controller.py", line 211, in get_predefined_actions_mapping
    Light.CLICK: self.click,
AttributeError: type object 'Light' has no attribute 'CLICK'```

**Comment by xaviml** [comment]
Hi @gumslone, are you using the code from the dev branch?

I recommend you installing a stable version, either manually or from HACS like indicated in the docs: https://xaviml.github.io/controllerx/start/installation

**Comment by gumslone** [comment]
hi, yes its from dev branch, thanks
