### ISSUE TITLE
Hue Dimmer switch Click "I" doesn't work [BUG]

### ISSUE THREAD

**Issue by moschu** [xaviml/controllerx#407]
# Bug report

## Description

Since yesterday all my Philips Hue dimmer switches do not work properly with ControllerX. When I click on "I", nothing happens. All other buttons are working fine. 
I checked the deconz_event and everything is fine. The event is displayed in Home Assistant. 

## Additional information 

* Devices involved:
  * Model: Philips Hue Dimmer switch as Controller
* Integration: deconn
* AppDaemon version: lastest
* ControllerX version: lastest
* HACS version (if installed from there): lastest
* Home Assistant Core version: lastest

## AppDaemon app configuration

```yaml
bad_schalter: 
  module: controllerx
  class: HueDimmerController
  controller: bad_schalter
  integration: deconz
  light: light.bad
  min_brightness: 30
  multiple_click_delay: 1
  mapping:
    1000:
      - service: input_select.select_next
        data:
          entity_id: input_select.bad
      - scene: "{{ states('input_select.bad') }}"
    2000: on_full_brightness
    3000: on_min_brightness
    4000: "off"
```

## Logs from AppDaemon

```2022-01-08 17:33:24.878039 WARNING bad_schalter: ------------------------------------------------------------
2022-01-08 17:33:24.878753 WARNING bad_schalter: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/appdaemon/threading.py", line 855, in async_worker
    await funcref(args["event"], data, self.AD.events.sanitize_event_kwargs(app, args["kwargs"]))
  File "/config/appdaemon/apps/controllerx/cx_core/integration/deconz.py", line 34, in event_callback
    await self.controller.handle_action(data[type_], extra=data)
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 352, in handle_action
    value = f"{value:.2f}"
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 426, in call_action
    async def multiple_click_call_action(self, kwargs: Dict[str, Any]) -> None:
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 464, in action_timer_callback
    )
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 482, in call_action_types
    )
  File "/config/appdaemon/apps/controllerx/cx_core/action_type/scene_action_type.py", line 14, in run
    await self.controller.call_service("scene/turn_on", entity_id=self.scene)
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 319, in call_service
    except (SyntaxError, ValueError):
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 309, in render_attributes
    return (
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 302, in render_value
    except ValueError:
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 286, in _render_template
    mapping.update(custom)
ValueError: Template {{ states('input_select.bad') }} returned None
2022-01-08 17:33:24.879076 WARNING bad_schalter: ------------------------------------------------------------
```

## Additional Context

Add any other context or screenshots about the bug here.

**Comment by xaviml** [comment]
Hi @moschu,

Sorry you are experiencing this. Please, read the following post to know more about your error: https://community.home-assistant.io/t/controllerx-bring-full-functionality-to-light-and-media-player-controllers/148855/1164?u=xaviml

I just released [ControllerX v4.18.1](https://github.com/xaviml/controllerx/releases/tag/v4.18.1) for this fix.

Regards,
Xavi M.
