### ISSUE TITLE
Error color_temp on Philips hue 

### ISSUE THREAD

**Issue by Sblackk** [xaviml/controllerx#534]
# Bug report

## Description

Hi. I have a problem with my 3 Ikea 1810 controllers and Philips lamps White and Color (EAN 8719514328204). Everything works except the color_temp adjustment (click and hold).  Could you give me a suggestion to solve this problem?  The on_min_color_temp and on_full_color_temp functions also work perfectly.  Thank you.
## Additional information

- Devices involved:
  - Model: IKEA 1810 
  - ...
- Integration: deconz 
- AppDaemon version: v0.91
- ControllerX version: v4.22.0
- HACS version (if installed from there): v1.26.2
- Home Assistant Core version: 2022.7.6

## AppDaemon app configuration

```
ikea_multicolor:
  module: controllerx
  class: E1810Controller
  controller: tradfri_remote_control
  integration: deconz
  light: light.extended_color_light_4
  delay: 500
  automatic_steps: 10
  manual_steps: 10
  merge_mapping:
    5001: 
      action: hold
      attribute: color_temp
      direction: down  #hold_colortemp_down
    4001: 
      action: hold
      attribute: color_temp
      direction: up  #hold_colortemp_up
    1002: toggle_full_brightness
    4002: click_colortemp_up
    5002:
      action: click_colortemp_down
```

## Logs

  File "/config/appdaemon/apps/controllerx/cx_core/integration/deconz.py", line 34, in event_callback

    await self.controller.handle_action(data[type_], extra=data)

  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 400, in handle_action
    await self.call_action(action_key, extra=extra)
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 474, in call_action
    await self.action_timer_callback({"action_key": action_key, "extra": extra})
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 512, in action_timer_callback
    await task
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 528, in call_action_types
    await action_type.run(extra=extra)
  File "/config/appdaemon/apps/controllerx/cx_core/action_type/predefined_action_type.py", line 118, in run
    await action(*positional, **action_args)
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 62, in _action_impl
    await method(controller, *args, **kwargs)
  File "/config/appdaemon/apps/controllerx/cx_core/type/light_controller.py", line 764, in click
    self.value_attribute = await self.get_value_attribute(attribute)
  File "/config/appdaemon/apps/controllerx/cx_core/type/light_controller.py", line 692, in get_value_attribute
    raise ValueError(
ValueError: Value for `color_temp` attribute could not be retrieved from `light.extended_color_light_4`. Check the FAQ to know more about this error: https://xaviml.github.io/controllerx/faq
2022-07-24 18:46:14.428040 WARNING ikea_multicolor: ------------------------------------------------------------
2022-07-24 18:46:15.527871 INFO ikea_multicolor: 馃幃 Button event triggered: `4002`
2022-07-24 18:46:15.538957 INFO ikea_multicolor: 馃弮 Running `Predefined (click_colortemp_up)` now
2022-07-24 18:46:15.552591 WARNING ikea_multicolor: ------------------------------------------------------------
2022-07-24 18:46:15.553799 WARNING ikea_multicolor: Unexpected error in worker for App ikea_multicolor:
2022-07-24 18:46:15.554930 WARNING ikea_multicolor: Worker Ags: {'id': '592051a44073419fa022c82a1de7722a', 'name': 'ikea_multicolor', 'objectid': '456dd9e671c54278b79fb5df39d077c0', 'type': 'event', 'event': 'deconz_event', 'function': <bound method DeCONZIntegration.event_callback of <cx_core.integration.deconz.DeCONZIntegration object at 0x7fab19bfa0>>, 'data': {'id': 'tradfri_remote_control', 'unique_id': '84:71:27:ff:fe:40:37:d6', 'event': 4002, 'device_id': '554bfc6bbe0b8e24d1a679b14007a38e', 'metadata': {'origin': 'LOCAL', 'time_fired': '2022-07-24T16:46:15.512082+00:00', 'context': {'id': '01G8RHMBER6T4N5BNZZJG8044D', 'parent_id': None, 'user_id': None}}}, 'pin_app': True, 'pin_thread': 8, 'kwargs': {'id': 'tradfri_remote_control', '__thread_id': 'MainThread'}}
2022-07-24 18:46:15.555923 WARNING ikea_multicolor: ------------------------------------------------------------
2022-07-24 18:46:15.557359 WARNING ikea_multicolor: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/threading.py", line 855, in async_worker
    await funcref(args["event"], data, self.AD.events.sanitize_event_kwargs(app, args["kwargs"]))
  File "/config/appdaemon/apps/controllerx/cx_core/integration/deconz.py", line 34, in event_callback
    await self.controller.handle_action(data[type_], extra=data)
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 400, in handle_action
    await self.call_action(action_key, extra=extra)
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 474, in call_action
    await self.action_timer_callback({"action_key": action_key, "extra": extra})
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 512, in action_timer_callback
    await task
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 528, in call_action_types
    await action_type.run(extra=extra)
  File "/config/appdaemon/apps/controllerx/cx_core/action_type/predefined_action_type.py", line 118, in run
    await action(*positional, **action_args)
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 62, in _action_impl
    await method(controller, *args, **kwargs)
  File "/config/appdaemon/apps/controllerx/cx_core/type/light_controller.py", line 764, in click
    self.value_attribute = await self.get_value_attribute(attribute)
  File "/config/appdaemon/apps/controllerx/cx_core/type/light_controller.py", line 692, in get_value_attribute
    raise ValueError(
ValueError: Value for `color_temp` attribute could not be retrieved from `light.extended_color_light_4`. Check the FAQ to know more about this error: https://xaviml.github.io/controllerx/faq
2022-07-24 18:46:15.559138 WARNING

## Additional Context

Add any other context or screenshots about the bug here.

**Comment by Sblackk** [comment]
ikea_multicolor:
  module: controllerx
  class: E1810Controller
  controller: tradfri_remote_control
  integration: deconz
  light: light.extended_color_light_4
  delay: 500
  automatic_steps: 10
  manual_steps: 10
  merge_mapping:
    5001: 
      action: hold
      attribute: color_temp
      direction: down  #hold_colortemp_down
    4001: 
      action: hold
      attribute: color_temp
      direction: up  #hold_colortemp_up
    1002: toggle_full_brightness
    4002: click_colortemp_up
    5002:
      action: click_colortemp_down

**Comment by xaviml** [comment]
Hi @Sblackk ,

As the error suggest, the FAQ says:

"""
5. Error: "Value for X attribute could not be retrieved from light Y"

This error is shown when the light has support for the X attribute (e.g. brightness or color_temp) and the attribute is not in the state attribute of the entity. You can check whether the attribute X is shown in the state attributes from the "Developer Tools > States".
"""

ControllerX needs to know what is the current color_temp value to gradually change it. So, this error means that your light is not exposing the color temperature attribute, which you can check in Developer Tools > States. It is expected that if the light supports color temperature, the value should be exposed as an attribute.

**Comment by Sblackk** [comment]
Fixed bug with "color wheel". Everything was working fine until I updated the lamp firmware. In fact, on the other Philips lamps with the old firmware I regulate the color temperature without problems. Thank you very much.
