### ISSUE TITLE
[QUESTION] E1810Controller support as media controller

### ISSUE THREAD

**Issue by ben-red42** [xaviml/controllerx#569]
# Question
Is the IKEA E1810 Controller can only be used to control light or can it control media players as well?
I'm getting a state of "initialize_error" when checking the APPS under the AppDaemon WebUI, The remote does trigger events in HA but nothing happens.
## Additional information
* Devices involved:
   * Model: E1810Controller
* Integration: deconz
* AppDaemon version: [ 0.9.3 ]
* ControllerX version: [ 4.22.0 ]
* HACS version (if installed from there): [ 1.27.1 ]
* Home Assistant Core version: [ 2022.9.1 ]

## AppDaemon app configuration
```
volumio:
  module: controllerx
  class: E1810Controller
  controller: tradfri_remote_basement
  integration: deconz
  volume_steps: 5
  media_player: media_player.volumio
```

## Logs
```
2022-09-09 23:30:37.188782 INFO AppDaemon: Starting Apps with 2 workers and 2 pins
2022-09-09 23:30:37.191248 INFO AppDaemon: Running on port 5050
2022-09-09 23:30:37.222730 INFO HASS: Evaluating startup conditions
2022-09-09 23:30:37.230492 INFO HASS: Startup condition met: hass state=RUNNING
2022-09-09 23:30:37.231023 INFO HASS: All startup conditions met
2022-09-09 23:30:37.276831 INFO AppDaemon: Got initial state from namespace default
2022-09-09 23:30:37.679816 INFO AppDaemon: Client disconnection from None
2022-09-09 23:30:39.199525 INFO AppDaemon: Scheduler running in realtime
2022-09-09 23:30:39.203264 INFO AppDaemon: Adding /config/appdaemon/apps to module import path
2022-09-09 23:30:39.203671 INFO AppDaemon: Adding /config/appdaemon/apps/controllerx to module import path
2022-09-09 23:30:39.203939 INFO AppDaemon: Adding /config/appdaemon/apps/controllerx/cx_core to module import path
2022-09-09 23:30:39.204282 INFO AppDaemon: Adding /config/appdaemon/apps/controllerx/cx_core/integration to module import path
2022-09-09 23:30:39.204576 INFO AppDaemon: Adding /config/appdaemon/apps/controllerx/cx_core/type to module import path
2022-09-09 23:30:39.204834 INFO AppDaemon: Adding /config/appdaemon/apps/controllerx/cx_core/feature_support to module import path
2022-09-09 23:30:39.205177 INFO AppDaemon: Adding /config/appdaemon/apps/controllerx/cx_core/stepper to module import path
2022-09-09 23:30:39.205450 INFO AppDaemon: Adding /config/appdaemon/apps/controllerx/cx_core/action_type to module import path
2022-09-09 23:30:39.205851 INFO AppDaemon: Adding /config/appdaemon/apps/controllerx/cx_devices to module import path
2022-09-09 23:30:39.234891 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/hello.py
2022-09-09 23:30:39.264924 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_helper.py - ignoring
2022-09-09 23:30:39.265696 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_const.py - ignoring
2022-09-09 23:30:39.266579 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_version.py - ignoring
2022-09-09 23:30:39.267363 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/controllerx/controllerx.py
2022-09-09 23:30:39.364896 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_core/__init__.py - ignoring
2022-09-09 23:30:39.365668 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_core/release_hold_controller.py - ignoring
2022-09-09 23:30:39.366476 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_core/controller.py - ignoring
2022-09-09 23:30:39.367024 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_core/color_helper.py - ignoring
2022-09-09 23:30:39.367792 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_core/type_controller.py - ignoring
2022-09-09 23:30:39.368406 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_core/integration/homematic.py - ignoring
2022-09-09 23:30:39.368952 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_core/integration/lutron_caseta.py - ignoring
2022-09-09 23:30:39.369555 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_core/integration/__init__.py - ignoring
2022-09-09 23:30:39.370263 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_core/integration/mqtt.py - ignoring
2022-09-09 23:30:39.372074 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_core/integration/state.py - ignoring
2022-09-09 23:30:39.372688 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_core/integration/zha.py - ignoring
2022-09-09 23:30:39.373433 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_core/integration/deconz.py - ignoring
2022-09-09 23:30:39.373988 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_core/integration/shellyforhass.py - ignoring
2022-09-09 23:30:39.374653 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_core/integration/z2m.py - ignoring
2022-09-09 23:30:39.375710 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_core/integration/shelly.py - ignoring
2022-09-09 23:30:39.376449 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_core/type/media_player_controller.py - ignoring
2022-09-09 23:30:39.377119 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_core/type/__init__.py - ignoring
2022-09-09 23:30:39.377651 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_core/type/switch_controller.py - ignoring
2022-09-09 23:30:39.378201 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_core/type/cover_controller.py - ignoring
2022-09-09 23:30:39.378799 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_core/type/light_controller.py - ignoring
2022-09-09 23:30:39.379429 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_core/type/z2m_light_controller.py - ignoring
2022-09-09 23:30:39.380065 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_core/feature_support/light.py - ignoring
2022-09-09 23:30:39.380692 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_core/feature_support/media_player.py - ignoring
2022-09-09 23:30:39.381567 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_core/feature_support/__init__.py - ignoring
2022-09-09 23:30:39.382251 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_core/feature_support/cover.py - ignoring
2022-09-09 23:30:39.383211 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_core/stepper/bounce_stepper.py - ignoring
2022-09-09 23:30:39.383975 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_core/stepper/__init__.py - ignoring
2022-09-09 23:30:39.384778 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_core/stepper/stop_stepper.py - ignoring
2022-09-09 23:30:39.385579 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_core/stepper/index_loop_stepper.py - ignoring
2022-09-09 23:30:39.386464 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_core/stepper/loop_stepper.py - ignoring
2022-09-09 23:30:39.387188 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_core/action_type/predefined_action_type.py - ignoring
2022-09-09 23:30:39.387771 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_core/action_type/delay_action_type.py - ignoring
2022-09-09 23:30:39.388603 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_core/action_type/__init__.py - ignoring
2022-09-09 23:30:39.389474 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_core/action_type/base.py - ignoring
2022-09-09 23:30:39.390507 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_core/action_type/scene_action_type.py - ignoring
2022-09-09 23:30:39.391371 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_core/action_type/call_service_action_type.py - ignoring
2022-09-09 23:30:39.392212 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_devices/ikea.py - ignoring
2022-09-09 23:30:39.393710 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_devices/muller_licht.py - ignoring
2022-09-09 23:30:39.395376 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_devices/homematic.py - ignoring
2022-09-09 23:30:39.396770 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_devices/smartthings.py - ignoring
2022-09-09 23:30:39.397566 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_devices/robb.py - ignoring
2022-09-09 23:30:39.398524 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_devices/__init__.py - ignoring
2022-09-09 23:30:39.399441 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_devices/rgb_genie.py - ignoring
2022-09-09 23:30:39.400208 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_devices/terncy.py - ignoring
2022-09-09 23:30:39.400829 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_devices/philips.py - ignoring
2022-09-09 23:30:39.401482 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_devices/lutron.py - ignoring
2022-09-09 23:30:39.402072 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_devices/osram.py - ignoring
2022-09-09 23:30:39.402711 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_devices/trust.py - ignoring
2022-09-09 23:30:39.403300 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_devices/linkind.py - ignoring
2022-09-09 23:30:39.403930 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_devices/tuya.py - ignoring
2022-09-09 23:30:39.404552 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_devices/livarno.py - ignoring
2022-09-09 23:30:39.405184 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_devices/aurora.py - ignoring
2022-09-09 23:30:39.405742 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_devices/sonoff.py - ignoring
2022-09-09 23:30:39.406291 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_devices/aqara.py - ignoring
2022-09-09 23:30:39.406938 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_devices/shelly.py - ignoring
2022-09-09 23:30:39.407469 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_devices/sengled.py - ignoring
2022-09-09 23:30:39.408074 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/controllerx/cx_devices/legrand.py - ignoring
2022-09-09 23:30:39.408556 INFO AppDaemon: Initializing app hello_world using class HelloWorld from module hello
2022-09-09 23:30:39.409679 INFO AppDaemon: Initializing app volumio using class E1810Controller from module controllerx
2022-09-09 23:30:39.470387 INFO hello_world: Hello from AppDaemon
2022-09-09 23:30:39.471152 INFO hello_world: You are now ready to run Apps!
2022-09-09 23:30:39.476130 INFO volumio: 🎮 ControllerX v4.22.0
2022-09-09 23:30:39.476509 WARNING volumio: ------------------------------------------------------------
2022-09-09 23:30:39.476718 WARNING volumio: Unexpected error running initialize() for volumio
2022-09-09 23:30:39.476942 WARNING volumio: ------------------------------------------------------------
2022-09-09 23:30:39.477835 WARNING volumio: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/app_management.py", line 163, in initialize_app
    await init()
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 104, in initialize
    await self.init()
  File "/config/appdaemon/apps/controllerx/cx_core/type/light_controller.py", line 148, in init
    await super().init()
  File "/config/appdaemon/apps/controllerx/cx_core/type_controller.py", line 54, in init
    raise ValueError(
ValueError: E1810Controller class needs the `light` attribute
2022-09-09 23:30:39.478164 WARNING volumio: ------------------------------------------------------------
2022-09-09 23:30:39.478852 INFO AppDaemon: App initialization complete
```

**Comment by xaviml** [comment]
Hi @ben-red42 ,

Yes, the E1810 controller can be used for a media player, but not with E1810Controller because it is a Light controller and expects a light. You want to use [E1810MediaPlayerController](https://xaviml.github.io/controllerx/controllers/E1810/#media-player). You can see in documentation which actions are performed for each event and you can modify the actions with [`mapping` or `merge_mapping`](https://xaviml.github.io/controllerx/advanced/).

Regards,
Xavi M.

**Comment by ben-red42** [comment]
Oh wow, I have no idea how I missed that one. Thank you!
Obviously, it works perfectly now.
