### ISSUE TITLE
Failing to load configurations

### ISSUE THREAD

**Issue by jonathanrelf** [xaviml/controllerx#622]
System setup:
Home Assistant 2022.11.0
Supervisor 2022.10.0
Operating System 9.3
Frontend 20221102.1 - latest
HACS 1.28.3
ControllerX V4.24.0
running on a Raspberry Pi 4

My ControllerX configuration is failing to work with the following errors for each configuration: 
```
2022-11-02 23:54:13.211748 WARNING office_light_switch: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/app_management.py", line 163, in initialize_app
    await init()
  File "/config/appdaemon/apps/controllerx/cx_devices/ikea.py", line 645, in initialize
    "stop_with_on_off": Light.RELEASE,
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 104, in initialize
    await self.init()
  File "/config/appdaemon/apps/controllerx/cx_core/type/light_controller.py", line 148, in init
    await super().init()
  File "/config/appdaemon/apps/controllerx/cx_core/type_controller.py", line 66, in init
    await super().init()
  File "/config/appdaemon/apps/controllerx/cx_core/release_hold_controller.py", line 27, in init
    await super().init()
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 108, in init
    self.integration = self.get_integration(self.args["integration"])
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 225, in get_integration
    integrations = integration_module.get_integrations(self, kwargs)
  File "/config/appdaemon/apps/controllerx/cx_core/integration/__init__.py", line 36, in get_integrations
    return integrations
  File "/config/appdaemon/apps/controllerx/cx_core/integration/__init__.py", line 36, in <listcomp>
    return integrations
TypeError: Can't instantiate abstract class EventIntegration with abstract method get_default_actions_mapping
2022-11-02 23:54:13.213168 WARNING office_light_switch: ------------------------------------------------------------

```

**Comment by xaviml** [comment]
Hi @jonathanrelf ,

Could you share also your apps.yaml, or the config for `office_light_switch`?

It is an error that I would not expect to see in any case... Could you also try reinstalling ControllerX through HACS and restart AppDaemon and check if error persists?

Thanks,
Xavi M.

**Comment by jonathanrelf** [comment]
Thank you for that suggestion. I'd restarted Home Assistant a couple of times with no effect. Seemingly reaffirming the installation, kicking AppDaemon and confirming things has seemingly ironed out the problems. 

Thanks for the swift response & suggestions. For reference I enclose the configuration of apps.yaml

```
jonathan_desk_switch:
  module: controllerx
  class: E1743Controller
  controller: sensor.jonathan_desk_lamp_switch_action
  integration: z2m
  light: light.jonathan_desk_lamp
  multiple_click_delay: 1000
  merge_mapping:
    "on$2":
      scene: scene.office_wall_light
    "on$3":
      scene: scene.office_2
    "off$2":
      scene: scene.office_off

office_light_switch:
  module: controllerx
  class: W2049LightController
  controller: sensor.office_light_switch_action
  integration: z2m
  light: light.office_light
```

**Comment by xaviml** [comment]
Hi @jonathanrelf ,

I realised that #623 had the same log problems as you. I know it is solved, but the reason was that AppDaemon addon needs to be restarted when ControllerX is updated. Otherwise, unexpected behaviour could happen as it happened to you.

In any case, I am glad that your problem was solved.

Regards,
Xavi M.
