### ISSUE TITLE
[BUG] WXKG11LMRemote doesn't work since update anymore

### ISSUE THREAD

**Issue by D-ominik** [xaviml/controllerx#623]
# Bug report
Since one of the last updates (have not updated for some month) my controller action doesn't work anymore. The controller WXKG11LM itself is working, issuing ZHA events.

## Additional information

- Devices involved:
  - Model: WXKG11LMRemote as Light Controller 
- Integration: `zha`
- AppDaemon version: 0.9.3
- ControllerX version: 4.24.0
- HACS version (if installed from there): 1.28.3
- Home Assistant Core version: 2022.11.0

## AppDaemon app configuration

```yaml
licht_arbeitszimmer_regeln:
  module: controllerx
  class: WXKG11LMRemoteLightController
  controller: 00:15:8d:00:04:01:97:3d
  integration: zha
  light: light.arbeitszimmer
```

## Logs

```text
2022-11-03 12:04:41.411464 INFO licht_arbeitszimmer_regeln: 🎮 ControllerX v4.22.0
2022-11-03 12:04:41.435055 WARNING licht_arbeitszimmer_regeln: ------------------------------------------------------------
2022-11-03 12:04:41.437788 WARNING licht_arbeitszimmer_regeln: Unexpected error in worker for App licht_arbeitszimmer_regeln:
2022-11-03 12:04:41.439650 WARNING licht_arbeitszimmer_regeln: Worker Ags: {}
2022-11-03 12:04:41.440541 WARNING licht_arbeitszimmer_regeln: ------------------------------------------------------------
2022-11-03 12:04:41.442646 WARNING licht_arbeitszimmer_regeln: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/app_management.py", line 163, in initialize_app
    await init()
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 104, in initialize
    await self.init()
  File "/config/appdaemon/apps/controllerx/cx_core/type/light_controller.py", line 148, in init
    await super().init()
  File "/config/appdaemon/apps/controllerx/cx_core/type_controller.py", line 66, in init
    await super().init()
  File "/config/appdaemon/apps/controllerx/cx_core/release_hold_controller.py", line 27, in init
    await super().init()
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 108, in init
    self.integration = self.get_integration(self.args["integration"])
  File "/config/appdaemon/apps/controllerx/cx_core/controller.py", line 225, in get_integration
    integrations = integration_module.get_integrations(self, kwargs)
  File "/config/appdaemon/apps/controllerx/cx_core/integration/__init__.py", line 36, in get_integrations
    return integrations
  File "/config/appdaemon/apps/controllerx/cx_core/integration/__init__.py", line 36, in <listcomp>
    return integrations
TypeError: Can't instantiate abstract class EventIntegration with abstract method get_default_actions_mapping
2022-11-03 12:04:41.443470 WARNING licht_arbeitszimmer_regeln: ------------------------------------------------------------
```

**Comment by xaviml** [comment]
Hi @D-ominik ,

As you can see in the logs, it is still executing ControllerX v4.22.0 and not v4.24.0. After ControllerX is updated, it is necessary to restart AppDaemon.

Regards,

**Comment by D-ominik** [comment]
Hi Xavi,
you are right, after manual restarting AppDaemon everthing is fine now again.

What I don't understand: I rebooted HomeAssistant yesterday after the HACS update. And today I rebooted again after a Home Assistant Core update. Why weren't these reboots enough?

Thanks a lot!

**Comment by xaviml** [comment]
Hi @D-ominik ,

AppDaemon (and any addon in general) runs in parallel from Home Assistant, so those restarts are not enough. The only 2 things that will work is if you either restart AppDaemon addon or restart de host machine.

Regards,
Xavi M.
