### ISSUE TITLE
get_entity_state called from initialize causes a crash in the app if the state cannnot be read

### ISSUE THREAD

**Issue by xaviml** [xaviml/controllerx#88]
# Bug report

## Description

ControllerX read the `supported_features` when the app is initialized. This means that if the light or any entity cannot be reached, then it causes a crash in the `initialize` function, which then causes a crash to the app

## Additional information

* AppDaemon version: v4.0.3
* ControllerX version: v2.7.1

## Logs

```text
2020-06-11 10:39:03.603598 WARNING halo_light_xiaomi: ------------------------------------------------------------
2020-06-11 10:39:03.603457 WARNING halo_light_xiaomi: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/appdaemon/app_management.py", line 143, in initialize_app
    await init()
  File "/conf/apps/controllerx/core/type/light_controller.py", line 118, in initialize
    self.supported_features = LightSupport(bitfield)
  File "/conf/apps/controllerx/core/feature_support/light.py", line 14, in __init__
    super().__init__(
  File "/conf/apps/controllerx/core/feature_support/__init__.py", line 21, in __init__
    parsed_number = int(number)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

2020-06-11 10:39:03.603129 WARNING halo_light_xiaomi: ------------------------------------------------------------
2020-06-11 10:39:03.603016 WARNING halo_light_xiaomi: Worker Ags: {}
2020-06-11 10:39:03.602875 WARNING halo_light_xiaomi: Unexpected error in worker for App halo_light_xiaomi:
2020-06-11 10:39:03.602678 WARNING halo_light_xiaomi: ------------------------------------------------------------
```

## Additional Context

To solve this, I propose to read the `supported_features` when an action is called and if it does not exist, then fetch the data. Otherwise, there is no need to fetching it.

**Comment by xaviml** [comment]
Fixed in ControllerX v2.8.0
